name: Smart Robot
on: [ push]
jobs:
  Yell-Watsup:
    runs-on: ubuntu-latest
    steps:
      - name: Yell Watsup
        run: echo " whats Up my brother"
      - name: Wake up
        run: echo "it is time to wake up"
        
  Check-up:
    runs-on: ubuntu-latest
    steps:
      - nam: Check Up message
        run: echo "Is everything okay, i have been trying to reach out to you"
  
    
